/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * AddDOCTOR.java
 *
 * Created on Nov 8, 2013, 11:03:44 PM
 */

/**
 *
 * @author sonal
 */
public class AddDOCTOR extends javax.swing.JFrame {

    /** Creates new form AddDOCTOR */
    public AddDOCTOR() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        TF3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TF1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TF5 = new javax.swing.JTextField();
        TF4 = new javax.swing.JTextField();
        TF6 = new javax.swing.JTextField();
        TF8 = new javax.swing.JTextField();
        TF7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TF2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sakkal Majalla", 1, 36)); // NOI18N
        jLabel1.setText("Add New Doctor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 0, -1, -1));

        jLabel11.setText("Date of Joining (YYYY-MM-DD):");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 256, -1, -1));

        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 96, -1, -1));

        jButton3.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 331, 84, -1));

        jButton2.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 331, 85, -1));

        jButton1.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 331, -1, -1));
        getContentPane().add(TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 141, -1));

        jLabel5.setText("Phone Number:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 173, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 54, 163, 10));
        getContentPane().add(TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 141, -1));

        jLabel4.setText("Address:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 148, -1, -1));
        getContentPane().add(TF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 141, -1));

        TF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF4ActionPerformed(evt);
            }
        });
        getContentPane().add(TF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 141, -1));
        getContentPane().add(TF6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 141, -1));
        getContentPane().add(TF8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 141, -1));
        getContentPane().add(TF7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 141, -1));

        jLabel10.setText("Cabin Number:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 285, -1, -1));

        jLabel7.setText("Department:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 205, -1, -1));

        jLabel8.setText("Fee (in Rupees):");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 231, -1, -1));

        jLabel3.setText("ID Number:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 121, -1, -1));
        getContentPane().add(TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 141, -1));

        jButton4.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 386, 147, 58));

        jButton5.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 331, 82, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add doctor.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 280, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF4ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_TF4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TF1.setText(null);
        TF3.setText(null);
        TF4.setText(null);
        TF5.setText(null);
        TF6.setText(null);
        TF2.setText(null);
        TF7.setText(null);
        TF8.setText(null);        
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try
     {
     Class.forName("java.sql.DriverManager");
     Connection c=DriverManager.getConnection("jdbc:mysql://"
             + "localhost:3306/op","root","1");
         String name,id,address,phno,dept,fee,doj,cabin;
         name=TF1.getText();
         id=TF2.getText();
   address=TF3.getText();
     phno=TF4.getText();
     dept=TF5.getText();
     fee=TF6.getText();
     doj=TF7.getText();
           cabin=TF8.getText();
           String q;
           q="insert into doctors values('"+name+"',"+id+",'"+address+"',"
                   + ""+phno+",'"+dept+"',"+fee+",'"+doj+"',"+cabin+")";
           Statement st=c.createStatement();
           st.executeUpdate(q);
JOptionPane.showMessageDialog(null,"Record Added");
     } catch(Exception e)
     { JOptionPane.showMessageDialog(null,"ERROR:  "+e.getMessage());
     }
     
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
this.setVisible(false);
new Main().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     this.setVisible(false);
new ADD().setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDOCTOR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF1;
    private javax.swing.JTextField TF2;
    private javax.swing.JTextField TF3;
    private javax.swing.JTextField TF4;
    private javax.swing.JTextField TF5;
    private javax.swing.JTextField TF6;
    private javax.swing.JTextField TF7;
    private javax.swing.JTextField TF8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
