/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * AddPATIENT.java
 *
 * Created on Nov 9, 2013, 11:06:57 AM
 */

/**
 *
 * @author sonal
 */
public class AddPATIENT extends javax.swing.JFrame {

    /** Creates new form AddPATIENT */
    public AddPATIENT() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        TF9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TF8 = new javax.swing.JTextField();
        TF4 = new javax.swing.JTextField();
        TF7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TF5 = new javax.swing.JTextField();
        TF6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TF1 = new javax.swing.JTextField();
        TF2 = new javax.swing.JTextField();
        TF3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 109, 10));

        jButton1.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 372, -1, -1));

        jLabel1.setFont(new java.awt.Font("Sakkal Majalla", 1, 24)); // NOI18N
        jLabel1.setText("Add New Patient");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jButton2.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 372, -1, -1));

        jButton3.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 372, -1, -1));

        TF9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF9ActionPerformed(evt);
            }
        });
        getContentPane().add(TF9, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 328, 141, 24));

        jLabel11.setForeground(new java.awt.Color(51, 255, 51));
        jLabel11.setText("Room Number:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 334, -1, 18));

        jLabel4.setText("Address:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 157, -1, 15));

        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 104, -1, 15));

        jLabel3.setText("ID Number:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 130, -1, 15));

        jLabel7.setText("Date of Admission (YYYY-MM-DD):");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 209, -1, 18));

        jLabel5.setText("Phone Number:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 184, -1, 15));

        TF8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF8ActionPerformed(evt);
            }
        });
        getContentPane().add(TF8, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 298, 141, 24));
        getContentPane().add(TF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 177, 141, -1));
        getContentPane().add(TF7, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 263, 141, 24));

        jLabel8.setText("Date of Discharge (YYYY-MM-DD):");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 239, -1, 18));
        getContentPane().add(TF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 203, 141, 24));
        getContentPane().add(TF6, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 233, 141, 24));

        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("Disease / Trouble:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 304, -1, 18));

        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("Payable Amount:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 269, -1, 18));
        getContentPane().add(TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 99, 141, -1));
        getContentPane().add(TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 125, 141, -1));

        TF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF3ActionPerformed(evt);
            }
        });
        getContentPane().add(TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 151, 141, -1));

        jButton4.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 433, 108, 51));

        jButton5.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 370, 81, 41));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 450, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try
     {
     Class.forName("java.sql.DriverManager");
     Connection c=DriverManager.getConnection("jdbc:mysql://localhost"
             + ":3306/op","root","1");
         String name,id,address,phno,doa,dod,amt,disease,room;
         name=TF1.getText();
         id=TF2.getText();
   address=TF3.getText();
     phno=TF4.getText();
     doa=TF5.getText();
     dod=TF6.getText();
     amt=TF7.getText();
     disease=TF8.getText();
           room=TF9.getText();
           String q;
          q="insert into patient values('"+name+"',"+id+",'"+address+"',"
           + ""+phno+",'"+doa+"','"+dod+"',"+amt+",'"+disease+"',"+room+")";
           Statement st=c.createStatement();
           st.executeUpdate(q);
JOptionPane.showMessageDialog(null,"Record Added");
     } catch(Exception e)
     { JOptionPane.showMessageDialog(null,"ERROR:  "+e.getMessage());
     }

}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TF1.setText(null);
        TF2.setText(null);
        TF3.setText(null);
        TF4.setText(null);
        TF5.setText(null);
        TF5.setText(null);
        TF6.setText(null);
        TF7.setText(null);
        TF8.setText(null);
        TF9.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
}//GEN-LAST:event_jButton3ActionPerformed

    private void TF9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF9ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_TF9ActionPerformed

    private void TF8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF8ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_TF8ActionPerformed

    private void TF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_TF3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
this.setVisible(false);
new Main().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
this.setVisible(false);
new ADD().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPATIENT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF1;
    private javax.swing.JTextField TF2;
    private javax.swing.JTextField TF3;
    private javax.swing.JTextField TF4;
    private javax.swing.JTextField TF5;
    private javax.swing.JTextField TF6;
    private javax.swing.JTextField TF7;
    private javax.swing.JTextField TF8;
    private javax.swing.JTextField TF9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
